[run]
branch = false
source = ["src"]
omit = [
    "tests/*",
    "src/grasping_ai/pipelines/visualize_robot.py",
]

[report]
show_missing = true
skip_covered = false
fail_under = 97
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
    "if TYPE_CHECKING:",
]
