[project]
name = "vr-rlft-side-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ntiensiit", email = "ntiensi.it@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.8",
    "pytest>=8",
    "pytest-cov>=6",
    "mypy>=1.13",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]
