target-version = "py312"
line-length = 120
src = ["src", "tests", "scripts"]
extend-exclude = [".venv", "build", "dist", "notebooks", "*.ps1"]

[lint]
select = ["ALL"]
# Text-style rules (not code or comments): copyright notices and exception-message wording.
ignore = ["CPY001", "EM101", "EM102", "TRY003"]

[lint.pydocstyle]
convention = "google"

[lint.isort]
known-first-party = ["grasping_ai", "scripts"]
force-to-top = ["open3d"]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
