# @package _global_
metrics:
  friction_coefficient: 0.5
  wrench_regularization: 1.0
  lift_height_threshold: 0.05
  collision_clearance: 0.005
limits:
  max_linear_velocity: 0.05
  max_angular_velocity: 0.1
evaluation:
  filter_collisions: false
  single_object_key: object_0
