# @package _global_
defaults:
  - default
  - _self_

notebook:
  experiment: evaluate_diffusion_flow_rl_colab

evaluation:
  method: diffusion
  analytical_report: ${model.exports.evaluation_report}
  simulation_report: ${model.exports.simulation_report}
