# @package _global_
defaults:
  - default
  - override /model: flow
  - _self_

evaluation:
  method: flow
  analytical_report: ${model.exports.evaluation_report}
  simulation_report: ${model.exports.simulation_report}
