# @package _global_
robot:
  description: deploy/robot.xml
  gripper:
    description: deploy/robot.xml
    close_command:
      - 0.0
    open_command:
      - 0.04
  ik:
    max_iterations: 400
    tolerance: 0.001
