# @package _global_
seed: 42
device: cpu
experiment_name: default
tracking:
  backend: none
  project: vr-rlft-side-project
  entity: null
  mode: offline
  mlflow:
    tracking_uri: ${oc.env:MLFLOW_TRACKING_URI,"./mlruns"}
    experiment_name: ${experiment_name}
