# @package _global_
artifacts:
  root: ${oc.env:MGS_OUTPUT_DIR,"artifacts"}
  checkpoints: ${artifacts.root}/checkpoints
  exports: ${artifacts.root}/exports
  reports: ${artifacts.root}/reports
  tensorboard: ${artifacts.root}/exports/tensorboard
