# @package _global_
objects:
  ids:
    - 003_cracker_box
    - 004_sugar_box
    - 005_tomato_soup_can
    - 009_gelatin_box
    - 010_potted_meat_can
    - 036_wood_block
    - 065-a_cups
    - 065-b_cups
    - 065-c_cups
    - 065-d_cups
    - 065-g_cups
    - 065-i_cups
    - 077_rubiks_cube
